source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

# Keep Ruby tooling on versions that include current security fixes.
gem 'cocoapods', '>= 1.16.2', '< 2.0'
gem 'activesupport', '>= 7.2.3.1', '!= 7.1.0'
gem 'xcodeproj', '>= 1.27.0', '< 2.0'
gem 'concurrent-ruby', '>= 1.3.7', '< 2.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
